Repository Keallar/Ragnarok, pull requests merged in 2021-12, with the labels that each got.

#96 New animations
  Classes/MainScene.cpp
  Classes/enemies/AgressiveBehaviour.cpp
  Classes/enemies/AgressiveBehaviour.h
  Classes/enemies/Enemy.cpp
  Classes/enemies/FlyingEnemy.cpp
  Classes/enemies/FlyingEnemy.h
  Classes/enemies/IEnemy.cpp
  Classes/enemies/IEnemy.h
  Classes/enemies/IEnemyBehaviour.h
  Classes/enemies/IEnemyType.h
  Classes/enemies/IdleBehaviour.cpp
  Classes/enemies/IdleBehaviour.h
  Classes/enemies/SimpleEnemy.cpp
  Resources/CloseNormal.png
  Resources/CloseSelected.png
  Resources/Flying_enemy_anim.png
  Resources/HelloWorld.png
  Resources/hp.png
  proj.win32/Ragnarok.vcxproj
  proj.win32/Ragnarok.vcxproj.filters
  proj.win32/imgui.ini
Labels: enhancement

#98 Test bullet bug
  Classes/IShootingPattern.cpp
  Classes/IShootingPattern.h
  Classes/MainScene.cpp
  Classes/MainScene.h
  Classes/Player.cpp
  Classes/PlayerHookBullet.cpp
  Classes/box2d/b2dSprite.cpp
  Classes/bullets/Bullet.cpp
  Classes/bullets/Bullet.h
  Classes/bullets/BulletFactory.cpp
  Classes/bullets/BulletFactory.h
  Classes/bullets/FireBullet.cpp
  Classes/bullets/FireBullet.h
  Classes/bullets/IBulletTypeCreator.cpp
  Classes/bullets/IBulletTypeCreator.h
  Classes/bullets/IceBullet.cpp
  Classes/bullets/IceBullet.h
  Resources/BigBullet.png
  Resources/Fire.png
  Resources/Hook.png
  Resources/Ice.png
  Resources/IceBlast.png
  Resources/Mega.png
  Resources/bullet.png
  proj.win32/FireBullet.cpp
  proj.win32/IceBullet.cpp
  proj.win32/Ragnarok.vcxproj
  proj.win32/Ragnarok.vcxproj.filters
  proj.win32/imgui.ini
Labels: bug, enhancement

#99 ice bullet & fire bullet
  Classes/IShootingPattern.cpp
  Classes/IShootingPattern.h
  Classes/MainScene.cpp
  Classes/Player.cpp
  Classes/Player.h
  Classes/PlayerHookBullet.cpp
  Classes/ShootingCharacter.cpp
  Classes/ShootingCharacter.h
  Classes/bullets/BigBullet.cpp
  Classes/bullets/Bullet.cpp
  Classes/bullets/Bullet.h
  Classes/bullets/FireBullet.cpp
  Classes/bullets/FireBullet.h
  Classes/bullets/IBulletMoveBehavior.cpp
  Classes/bullets/IBulletMoveBehavior.h
  Classes/bullets/IBulletTypeCreator.cpp
  Classes/bullets/IBulletTypeCreator.h
  Classes/bullets/IceBullet.cpp
  Classes/bullets/IceBullet.h
  Classes/enemies/IEnemy.cpp
  Classes/enemies/IEnemy.h
  Resources/BigFire.png
  Resources/Fire.png
  proj.win32/Ragnarok.vcxproj
  proj.win32/Ragnarok.vcxproj.filters
  proj.win32/imgui.ini
Labels: enhancement

#100 Anti ray cast
  Classes/ContactListener.cpp
  Classes/MainScene.cpp
  Classes/MainScene.h
  Classes/TileMapManager.cpp
  Classes/Trigger.cpp
  Classes/Trigger.h
  Classes/box2d/b2dSprite.cpp
  Classes/box2d/b2dSprite.h
  Resources/6fdc2ee9-e692-419c-a19f-f9de4a93a09a.png
  Resources/AEEEEE.tsx
  Resources/CloseNormal..tsx
  Resources/IMG_1246 (2).png
  Resources/IMG_1246.PNG
  Resources/Test.tmx
  Resources/Texture1.png
  Resources/Texture1.tsx
  Resources/desert_tileset.tsx
  Resources/last.tmx
  Resources/maximum.tmx
  Resources/tiles.png
  Resources/tileset_v2.tsx
  Resources/tileset_v3.tsx
  Resources/tmw_desert_spacing.png
  Resources/tmw_desert_spacing.tsx
  Resources/ver2.tmx
  proj.win32/Ragnarok.vcxproj
  proj.win32/Ragnarok.vcxproj.filters
Labels: enhancement

#105 Fix enemy animation init
  Classes/enemies/Enemy.cpp
  Resources/nodeProperties/enemies.json
Labels: bug

#107 Agressive behaviour for Flying enemy
  Classes/MainScene.cpp
  Classes/enemies/AgressiveBehaviour.cpp
  Classes/enemies/AgressiveBehaviour.h
  Classes/enemies/Enemy.cpp
  Classes/enemies/IEnemy.cpp
  Classes/enemies/IEnemy.h
  Classes/enemies/IEnemyBehaviour.h
  Classes/enemies/IdleBehaviour.cpp
  Classes/enemies/IdleBehaviour.h
  Classes/player/Player.cpp
  Classes/player/Player.h
  Classes/ui/HUD.cpp
  Resources/images/Wolf.png
  Resources/nodeProperties/enemies.json
  Resources/nodeProperties/player.json
  proj.win32/imgui.ini
Labels: enhancement

#114 Fix move anim state after falling
  Classes/MainScene.cpp
  Classes/contactListener/ContactListener.cpp
  Classes/enemies/IdleBehaviour.cpp
  Classes/player/Player.cpp
  Classes/player/Player.h
Labels: bug

#120 All enemies are created
  Classes/MainScene.cpp
  Classes/enemies/AgressiveBehaviour.cpp
  Classes/enemies/Enemy.cpp
  Classes/enemies/IEnemy.h
  Classes/player/Player.cpp
  Classes/player/Player.h
  Resources/images/Flying_enemy_anim.png
  Resources/images/Flying_enemy_idle_anim.png
  Resources/images/Flying_enemy_moveL_anim.png
  Resources/images/Flying_enemy_moveR_anim.png
  Resources/images/PAPAABOBA.png
  Resources/images/PAPAABOBA_attack_anim.png
  Resources/images/Turtle.png
  Resources/images/Turtle_attack_anim.png
  Resources/nodeProperties/enemies.json
  Resources/nodeProperties/player.json
  proj.win32/Ragnarok.vcxproj
  proj.win32/Ragnarok.vcxproj.filters
Labels: bug, enhancement

#121 Added background
  Classes/enemies/IEnemy.cpp
  Classes/enemies/IEnemy.h
  Resources/images/Clouds.png
  Resources/images/Mountain_back.png
  Resources/images/Mountains.png
  Resources/images/Sky.png
  Resources/images/background.png
  proj.win32/Ragnarok.vcxproj
  proj.win32/Ragnarok.vcxproj.filters
Labels: enhancement

#124 Refactoring enemies
  Classes/MainScene.cpp
  Classes/box2d/b2dSprite.h
  Classes/characters/MeleeCharacter.cpp
  Classes/characters/MeleeCharacter.h
  Classes/contactListener/ContactListener.cpp
  Classes/enemies/AgressiveBehaviour.cpp
  Classes/enemies/Boss.h
  Classes/enemies/Enemy.cpp
  Classes/enemies/IEnemy.cpp
  Classes/enemies/IEnemy.h
  Classes/enemies/IdleBehaviour.cpp
  Classes/player/Player.cpp
  Classes/player/Player.h
  Resources/images/Boss.png
  Resources/images/Boss_attack_anim.png
  Resources/images/Flying_enemy_moveR_anim.png
  Resources/images/Flying_enemy_move_anim.png
  Resources/nodeProperties/enemies.json
  Resources/player.json
  Resources/sounds/Fall.mp3
  Resources/sounds/Step.mp3
  proj.win32/Ragnarok.vcxproj
  proj.win32/Ragnarok.vcxproj.filters
  proj.win32/imgui.ini
Labels: bug, enhancement

#125 Added step sound
  Classes/MainScene.cpp
  Classes/enemies/AgressiveBehaviour.cpp
  Classes/enemies/Enemy.cpp
  Classes/enemies/IEnemy.cpp
  Classes/player/Player.cpp
Labels: enhancement

#129 Fix Aboba enemy
  Classes/enemies/IEnemy.cpp
  Classes/player/Player.cpp
  Resources/nodeProperties/bullets.json
  Resources/nodeProperties/player.json
  proj.win32/Ragnarok.vcxproj
  proj.win32/Ragnarok.vcxproj.filters
Labels: enhancement

#131 hook on right mouse button + new impulse & jump
  Classes/MainMenu.cpp
  Classes/bullets/PlayerHookBullet.cpp
  Classes/bullets/PlayerHookBullet.h
  Classes/player/Player.cpp
  proj.win32/imgui.ini
Labels: bug

#132 Hook new2
  Classes/player/Player.cpp
Labels: bug

#134 Aboba enemy
  Classes/MainScene.cpp
  Classes/MainScene.h
  Classes/enemies/AgressiveBehaviour.cpp
  Classes/enemies/Boss.cpp
  Classes/enemies/Boss.h
  Classes/enemies/Enemy.cpp
  Classes/enemies/IEnemy.cpp
  Resources/images/Boss.png
  Resources/images/Boss_attack_anim.png
  Resources/nodeProperties/enemies.json
Labels: bug, enhancement

#135 Changes behaviour of simple enemy and added deathless player
  Classes/MainScene.cpp
  Classes/MainScene.h
  Classes/enemies/AgressiveBehaviour.cpp
  Classes/enemies/AgressiveBehaviour.h
  Classes/enemies/Boss.cpp
  Classes/enemies/Boss.h
  Classes/enemies/Enemy.cpp
  Classes/enemies/IdleBehaviour.cpp
  Classes/player/Player.cpp
  Classes/player/Player.h
  Resources/bullets.json
  Resources/nodeProperties/enemies.json
  Resources/player.json
  proj.win32/imgui.ini
Labels: enhancement

#136 Damage
  Classes/MainScene.cpp
  Classes/Trigger.cpp
  Classes/bullets/BigBullet.cpp
  Classes/bullets/BigBullet.h
  Classes/bullets/Bullet.cpp
  Classes/bullets/Bullet.h
  Classes/bullets/FireBullet.cpp
  Classes/bullets/FireBullet.h
  Classes/bullets/IBulletTypeCreator.cpp
  Classes/bullets/IBulletTypeCreator.h
  Classes/bullets/IceBullet.cpp
  Classes/bullets/IceBullet.h
  Classes/bullets/PlayerHookBullet.cpp
  Classes/bullets/PlayerHookBullet.h
  Classes/characters/ShootingCharacter.cpp
  Classes/characters/ShootingCharacter.h
  Classes/contactListener/ContactListener.cpp
  Classes/enemies/AgressiveBehaviour.cpp
  Classes/enemies/Enemy.cpp
  Classes/enemies/IEnemy.cpp
  Classes/enemies/IEnemy.h
  Classes/player/Player.cpp
  Resources/bullet.png
  proj.win32/imgui.ini
Labels: bug, enhancement

#137 Added attack anim
  Classes/MainScene.cpp
  Classes/player/Player.cpp
  Resources/images/Tur_attack_anim.png
  Resources/nodeProperties/player.json
Labels: enhancement

#139 added win screen & boss some fix
  Classes/MainMenu.cpp
  Classes/MainMenu.h
  Classes/MainScene.cpp
  Classes/MainScene.h
  Classes/box2d/b2dRootWorldNode.cpp
  Classes/contactListener/ContactListener.cpp
  Classes/enemies/AgressiveBehaviour.cpp
  Classes/enemies/Boss.cpp
  Classes/enemies/Boss.h
  Classes/enemies/IEnemy.h
  Classes/ui/HUD.cpp
  Classes/ui/HUD.h
  Resources/images/win.png
  proj.win32/imgui.ini
Labels: enhancement

#140 message at start
  Classes/MainScene.cpp
  Classes/ui/HUD.cpp
  Classes/ui/NoticeBox.cpp
Labels: enhancement
